version: "3"

services: 
  app:
    image: app
    container_name: app
    build: ./
    restart: always
    ports: 
      - "81:80"
    volumes: 
      - .:/var/www/html

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on: 
      - mysql
    ports: 
      - "82:80"
    links: 
      - mysql:db
      
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    ports: 
      - "3307:3306"
    volumes: 
      - mysql:/var/lib/mysql
    environment:
      MYSQL_HOST: 0.0.0.0
      MYSQL_ROOT_PASSWORD: root

volumes: 
  mysql:
    driver: "local"

